### ISSUE TITLE
Blank document by default

### ISSUE THREAD

**Issue by Odepia** [brunophilipe/Noto#3]
I like Noto and I use it everyday. 
I would love to have an option allowing to open Noto with a blank document by default. That will be great!

**Comment by brunophilipe** [comment]
Thanks for the feedback!

It sounds like a cool idea to have that as an option. Opening the document browser by default is the Apple recommended behavior for iCloud supported apps, but I like having that as a user customizable feature.

In the meanwhile, you might try this new tiny feature from the latest version (1.2) of right-clicking the dock icon and selecting “new document”. :)

**Comment by Odepia** [comment]
Thank you for the tip, this is a good workaround.

Hope an option will be available in a future version. Not a big deal for now :)

Keep going your good work with Noto! :)
